# Generated by Django 5.2.3 on 2026-07-17 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Booking', '0003_rename_status_booking_status_booking'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id_assignment', models.AutoField(primary_key=True, serialize=False)),
                ('task', models.CharField(max_length=500)),
                ('status_assignment', models.CharField(max_length=500)),
                ('id_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Booking.booking')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.user')),
            ],
            options={
                'verbose_name': 'Assigntment',
                'verbose_name_plural': 'Assigntments',
                'db_table': 'assignment',
            },
        ),
    ]
