# Generated by Django 5.2.3 on 2026-07-26 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Assignments', '0002_alter_assignment_id_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='id_assignment',
            new_name='id',
        ),
    ]
