# Generated by Django 5.2.3 on 2026-07-20 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Role', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='description_role',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='id_role',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='name_role',
            new_name='name',
        ),
    ]
