# Generated by Django 5.2.3 on 2026-07-16 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Airport', '0001_initial'),
        ('Role', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('name_user', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=3)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('id_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Airport.airport')),
                ('id_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Role.role')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'user',
            },
        ),
    ]
