# Generated by Django 5.2.3 on 2026-07-17 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Airport', '0001_initial'),
        ('User', '0001_initial'),
        ('Vehicle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id_booking', models.AutoField(primary_key=True, serialize=False)),
                ('datetime_checkin', models.DateTimeField(max_length=100)),
                ('datetime_checkout', models.DateTimeField(max_length=100)),
                ('associated_flight', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('id_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Airport.airport')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.user')),
                ('id_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vehicle.vehicle')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'bookings',
                'db_table': 'booking',
            },
        ),
    ]
