# Generated by Django 5.2.3 on 2026-07-17 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0001_initial'),
        ('Service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingServices',
            fields=[
                ('id_bookingservices', models.AutoField(primary_key=True, serialize=False)),
                ('aplied_price', models.FloatField(max_length=100)),
                ('id_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Booking.booking')),
                ('id_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Service.service')),
            ],
            options={
                'verbose_name': 'Booking-Service',
                'verbose_name_plural': 'Bookings-Services',
                'db_table': 'booking-service',
            },
        ),
    ]
