# Generated by Django 5.2.3 on 2026-07-17 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0002_bookingservices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='status',
            new_name='status_booking',
        ),
    ]
