# Generated by Django 5.2.3 on 2026-07-16 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id_vehicle', models.AutoField(primary_key=True, serialize=False)),
                ('plate_number', models.IntegerField(max_length=200)),
                ('car_make', models.CharField(max_length=3)),
                ('car_model', models.CharField(blank=True, max_length=200, null=True)),
                ('car_color', models.CharField(blank=True, max_length=200, null=True)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vehiculo',
                'verbose_name_plural': 'Vehiculos',
                'db_table': 'vehicle',
            },
        ),
    ]
