# Generated by Django 5.2.3 on 2026-07-23 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_user_options_alter_user_id_user_and_more'),
        ('Vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.user'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='plate_number',
            field=models.IntegerField(),
        ),
    ]
