# Generated by Django 5.2.3 on 2026-07-26 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicle', '0002_alter_vehicle_id_user_alter_vehicle_plate_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='id_vehicle',
            new_name='id',
        ),
    ]
