# Generated by Django 5.2.3 on 2026-07-26 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicle', '0003_rename_id_vehicle_vehicle_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='car_make',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='plate_number',
            field=models.CharField(max_length=7),
        ),
    ]
