# Generated by Django 5.2.3 on 2026-07-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id_bill', models.AutoField(primary_key=True, serialize=False)),
                ('service_provider', models.CharField(blank=True, max_length=200, null=True)),
                ('pay_status', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Bill',
                'verbose_name_plural': 'Bills',
                'db_table': 'bill',
            },
        ),
    ]
