# Generated by Django 5.2.3 on 2026-07-17 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Bill', '0001_initial'),
        ('Booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='id_booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Booking.booking'),
        ),
    ]
