# Generated by Django 5.2.3 on 2026-07-26 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bill', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='id_bill',
            new_name='id',
        ),
    ]
