# Generated by Django 5.2.3 on 2026-07-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id_airport', models.AutoField(primary_key=True, serialize=False)),
                ('name_airport', models.CharField(max_length=200)),
                ('IATA_code', models.CharField(max_length=3)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Aeropuerto',
                'verbose_name_plural': 'Aeropuertos',
                'db_table': 'airport',
            },
        ),
    ]
