# Generated by Django 5.2.3 on 2026-07-20 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Airport', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airport',
            old_name='id_airport',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='airport',
            old_name='name_airport',
            new_name='name',
        ),
    ]
